version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"